base_measure_params:
  alpha: 1
  beta: 1
beta_binomial_precision_params:
  prior:
    rate: 0.001
    shape: 1.0
  proposal:
    precision: 0.01
  value: 1000
concentration:
  prior:
    rate: 0.001
    shape: 1.0
  value: 1.0
density: pyclone_beta_binomial
init_method: connected
num_iters: 5000
max_clusters: 100
samples:
  sample1_pyclone:
    error_rate: 0.001
    mutations_file: $mutation_file_full_path
    tumour_content:
      value: 1.0
trace_dir: trace
working_dir: $outdir_full_path
